config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'sub_order_generals/destroy'
  devise_for :users,
             path: '', # optional namespace or empty string for no space
             path_names: {
               sign_in: 'login',
               sign_out: 'logout',
               password: 'secret',
               confirmation: 'verification',
               registration: 'register',
               sign_up: 'signup'
             }

  get 'active'  => 'sessions#active'
  get 'timeout' => 'sessions#timeout'

  get 'nosuboarchivos' => 'secrets#new'
  get 'global_report' => 'reports#global'

  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :orders, param: :slug do
    resources :sub_orders, param: :slug
  end

  post '/hospital_charges', to: 'hospital_charges#create'
  get '/hospital_charges/:user_id', to: 'hospital_charges#index'
  delete '/hospital_charges/:id', to: 'hospital_charges#destroy'

  resources :orders, param: :slug
  get '/pending/orders', to: 'orders#pending'

  resources :report_orders
  resources :sub_orders, param: :slug
  get '/sub_orders/one/:id', to: 'sub_orders#get_sub_order'
  resources :doctors
  resources :hospitals do
    resources :sufferings, only: %i[index]
    resources :procedures, only: %i[index]
  end
  resources :providers, param: :slug
  post '/providers/hold', to: 'providers#on_hold'
  resources :users, param: :slug
  resources :generic_materials
  resources :general_materials, only: %i[index]
  resources :provider_materials
  resources :hospital_supervisions, only: %i[index show update]
  resources :hospital_supervision_provider_orders, only: %i[index show update]

  get '/cancelations/last_ten', to: 'cancelations#last_ten'
  resources :cancelations, only: %i[index show update]
  resources :intelligence_centers, only: %i[index show update]
  resources :dictums, only: %i[index show]
  resources :icds, only: %i[index create]
  resources :cpts, only: %i[index create]

  resources :file_uploaders
  resources :provider_payments
  resources :provider_deliveries
  resources :provider_qualities, only: %i[index show update]
  resources :negotiations
  resources :provider_negotiations, only: %i[index show update]
  resources :material_negotiations, only: %i[index show update]
  resources :case_managements
  resources :new_supplies, only: %i[index show update]
  
  resources :sub_order_generals, only: %i[destroy]
  resources :qualities, only: %i[index show update]
  resources :extemporaneous, only: %i[index show update]
  resources :operational_consultings, only: %i[index show]
  get '/operational_consulting/last_ten', to: 'operational_consultings#last_ten'
  resources :operational_consulting_providers, only: %i[index show]
  get '/operational_consulting_provider/last_ten', to: 'operational_consulting_providers#last_ten'
  resources :documents, only: %i[destroy]
  resources :overuse
  get '/overuse/:id/sub_orders', to: 'overuse#sub_orders'
end

app/controllers/cancelations_controller.rb
class CancelationsController < ApplicationController
  protect_from_forgery except: %i[index last_ten]
  before_action :authenticate_user!
  before_action :set_sub_order, only: %i[show update]

  def index
    @sub_orders = SubOrder.search(params[:search])
                    .includes([{ order: %i[doctor hospital] }])
                    .where(status: [
                      'case_management', 'cdi', 'hospital_supervision', 'negotiable-matter','pending', 'supplier_management'
                    ])
                    .paginate(page: params[:page])
                    .order(order_id: :desc)

    respond_to do |format|
      format.js { render json: @sub_orders, status: :ok }
      format.html
    end
  end

  def show
    respond_to do |format|
      format.js { render json: @sub_order, status: :ok }
      format.html
    end
  end

  def update
    @sub_order.update(
      status: params[:sub_order][:status],
      cancelation_motive: params[:sub_order][:cancelation_motive],
      cancellation_comment: params[:sub_order][:cancellation_comment],
      cancelation_date: Time.now
    )

    @sub_order.comments.create(
      comment: params[:comment][:comment],
      user: params[:comment][:user],
      module: params[:comment][:module],
      date: (Time.now - 5*60*60).strftime('%d-%m-%Y %I:%M:%S %p')
    )

    flash[:success] = params[:message]
    render json: { status: :ok }
  end

  private

  def set_sub_order
    @sub_order = SubOrder.find_by slug: params[:id]
  end

  def sub_order_params
    params.require(:sub_order).permit(:status, :cancelation_motive, :cancellation_comment)
  end

end

app/helpers/cancelations_helper.rb
module CancelationsHelper
end

app/views/cancelations/index.html.erb
<h1>Cancelaciones</h1>

<%= form_tag cancelations_path, :method => 'get' do %>
  <div class="row">
    <%= text_field_tag :search, params[:search], class: 'form-control col-11' %>
    <%= submit_tag 'Buscar', :name => nil, class: 'btn btn-primary col-1' %>
  </div>
<% end %>

<br><br>
<%- if @sub_orders.size < 1  %>
    <div class="alert alert-danger" role="alert">
        No se encontro informacion.
    </div>
<% end %>
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">Ticket CPO</th>
            <th scope="col">Codificado</th>
            <th scope="col">Tipo de trámite</th>
            <th scope="col">Asegurado</th>
            <th scope="col">Folio GNP</th>
            <th scope="col">Reclamación</th>
            <th scope="col">Hospital</th>
            <th scope="col">Estado</th>
            <th scope="col">Medico Tratante</th>
            <th scope="col">Proveedor</th>
            <th scope="col">Ver</th>
        </tr>
        </thead>
        <tbody>
        <%- @sub_orders.each do |sub_order|  %>
            <% if can? :show, sub_order %>
                <tr>
                    <td><%= sub_order.cpo %></td>
                    <% if sub_order.coded %>
                        <td style="color: green">
                            codificado
                        </td>
                    <% else %>
                        <td style="color: red">
                            no codificado
                        </td>
                    <% end %>
                    <td><%= sub_order.order.order_type %></td>
                    <td><%= sub_order.order.insured %></td>
                    <td><%= sub_order.order.gnp_invoice %></td>
                    <td><%= sub_order.order.claim %></td>
                    <td><%= sub_order.order.hospital.name %></td>
                    <td><%= sub_order.order.hospital.state %></td>
                    <td><%= sub_order.order.doctor.name %></td>
                    <td><%= sub_order.provider.name %></td>
                    <td>
                        <%= link_to('Ver', cancelation_path(sub_order))%>       
                    </td>
                </tr>
            <% end %>
        <% end %>
        </tbody>
    </table>
</div>
<%= will_paginate @sub_orders, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

app/views/cancelations/show.html.erb
<%= react_component('CancelationOrder',{
    sub_order: @sub_order,
    order: @sub_order.order,
    authenticity_token: form_authenticity_token,
    username: current_user.username,
    module: 'Cancelación' 
}) %>

app/views/cancelations/update.html.erb
<h1>Cancelations#update</h1>
<p>Find me in app/views/cancelations/update.html.erb</p>