config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'sub_order_generals/destroy'
  devise_for :users,
             path: '', # optional namespace or empty string for no space
             path_names: {
               sign_in: 'login',
               sign_out: 'logout',
               password: 'secret',
               confirmation: 'verification',
               registration: 'register',
               sign_up: 'signup'
             }

  get 'active'  => 'sessions#active'
  get 'timeout' => 'sessions#timeout'

  get 'nosuboarchivos' => 'secrets#new'
  get 'global_report' => 'reports#global'

  devise_scope :user do
    authenticated :user do
      root 'dashboard#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :orders, param: :slug do
    resources :sub_orders, param: :slug
  end

  post '/hospital_charges', to: 'hospital_charges#create'
  get '/hospital_charges/:user_id', to: 'hospital_charges#index'
  delete '/hospital_charges/:id', to: 'hospital_charges#destroy'

  resources :orders, param: :slug
  get '/pending/orders', to: 'orders#pending'

  resources :report_orders
  resources :sub_orders, param: :slug
  get '/sub_orders/one/:id', to: 'sub_orders#get_sub_order'
  resources :doctors
  resources :hospitals do
    resources :sufferings, only: %i[index]
    resources :procedures, only: %i[index]
  end
  resources :providers, param: :slug
  post '/providers/hold', to: 'providers#on_hold'
  resources :users, param: :slug
  resources :generic_materials
  resources :general_materials, only: %i[index]
  resources :provider_materials
  resources :hospital_supervisions, only: %i[index show update]
  resources :hospital_supervision_provider_orders, only: %i[index show update]

  get '/cancelations/last_ten', to: 'cancelations#last_ten'
  resources :cancelations, only: %i[index show update]
  resources :intelligence_centers, only: %i[index show update]
  resources :dictums, only: %i[index show]
  resources :icds, only: %i[index create]
  resources :cpts, only: %i[index create]

  resources :file_uploaders
  resources :provider_payments
  resources :provider_deliveries
  resources :provider_qualities, only: %i[index show update]
  resources :negotiations
  resources :provider_negotiations, only: %i[index show update]
  resources :material_negotiations, only: %i[index show update]
  resources :case_managements
  resources :new_supplies, only: %i[index show update]
  
  resources :sub_order_generals, only: %i[destroy]
  resources :qualities, only: %i[index show update]
  resources :extemporaneous, only: %i[index show update]
  resources :operational_consultings, only: %i[index show]
  get '/operational_consulting/last_ten', to: 'operational_consultings#last_ten'
  resources :operational_consulting_providers, only: %i[index show]
  get '/operational_consulting_provider/last_ten', to: 'operational_consulting_providers#last_ten'
  resources :documents, only: %i[destroy]
  resources :overuse
  get '/overuse/:id/sub_orders', to: 'overuse#sub_orders'
end

app/controllers/provider_negotiations_controller.rb
# frozen_string_literal: true

class ProviderNegotiationsController < ApplicationController
  protect_from_forgery except: %i[index show]
  before_action :authenticate_user!
  before_action :set_sub_order, only: %i[show update]
  before_action :set_provider, only: %i[update]

  def index
    @sub_orders = SubOrder.where(status: 'supplier_management')
                          .includes([{ order: %i[
                                      doctor
                                      hospital
                                    ] }])
                          .paginate(page: params[:page])
                          .order(order_id: :desc)
  end

  def show
    respond_to do |format|
      format.js { render json: @sub_order, status: :ok }
      format.html
    end
  end

  def update
    result = ProcessProviderNegotiation.call(
      sub_order: @sub_order,
      sub_order_params: sub_order_params,
      comment: params[:comment],
      documents: params[:documents],
      provider: @provider,
      provider_params: provider_params,
      materials: params[:materials],
      current_user: current_user
    )

    if result.success?
      flash[:success] = params[:message] || 'Guardado Exitoso'
      render json: { status: :ok }
    else
      render json: { status: :unprocessable_entity }
    end
  end

  private

  def set_order
    @order = Order.find params[:id]
  end

  def set_sub_order
    @sub_order = SubOrder.find_by slug: params[:id]
  end

  def set_provider
    @provider = Provider.find params[:provider][:provider_id]
  end

  def provider_params
    params.require(:provider).permit(:status, :responsable, :contact_number, :provider_negotiation_type, :affiliate_code)
  end

  def sub_order_params
    params.require(:sub_order).permit(:status, :coded)
  end
end

app/views/provider_negotiations/index.html.erb
<h1>NEGOCIACIÓN DE PROVEEDORES</h1>

<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th scope="col">Ticket CPO</th>
            <th scope="col">Tipo de Programación</th>
            <th scope="col">Asegurado</th>
            <th scope="col">Médico Tratante</th>
            <th scope="col">Hospital</th>
            <th scope="col">Estado</th>
            <th scope="col">Procedimiento</th>
            <th scope="col">Opciones</th>
        </tr>
        </thead>
        <tbody>
        <%- @sub_orders.each do |sub_order|  %>
            <% if can? :show, sub_order %>
                <tr>
                    <td><%= sub_order.cpo %></td>
                    <td><%= sub_order.order.order_type %></td>
                    <td><%= sub_order.order.insured %></td>
                    <td><%= sub_order.order.doctor.name %></td>
                    <td><%= sub_order.order.hospital.name %></td>
                    <td><%= sub_order.order.hospital.state %></td>
                    <td><%= sub_order.order.procedure %></td>
                    <td>
                        <%= link_to('Ir', provider_negotiation_path(sub_order))%>       
                    </td>
                </tr>
            <% end %>
        <% end %>
        </tbody>
    </table>
</div>
<%= will_paginate @sub_orders, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

app/views/provider_negotiations/show.html.erb
<%= react_component('ProviderNegotiation', { 
    authenticity_token: form_authenticity_token,
    sub_order: @sub_order,
    order: @sub_order.order,
    username: current_user.username,
    module: 'Negociación Proveedores' 
}) %>